pvrdma: update main.c qdev property import
...it was moved a layer deeper into core/*
in latest qemu project upstream.

```
[2/1976] Compiling C object libqemu-aarch64-softmmu.a.p/hw_rdma_vmw_pvrdma_main.c.o
FAILED: [code=1] libqemu-aarch64-softmmu.a.p/hw_rdma_vmw_pvrdma_main.c.o
cc -m64 -Ilibqemu-aarch64-softmmu.a.p -I. -I.. -Itarget/arm -I../target/arm -Isubprojects/libvduse -I../subprojects/libvduse -Iqapi -Itrace -Iui -Iui/shader -I/usr/include/capstone -I/usr/include/p11-kit-1 -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/spice-server -I/usr/include/spice-1 -I/usr/include/SDL2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/slirp -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/webp -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/vte-2.91 -I/usr/include/virgl -I/usr/include/cacard -I/usr/include/libusb-1.0 -I/usr/include/fuse3 -I/usr/include/uuid -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -fdiagnostics-color=auto -Wall -Winvalid-pch -Werror -std=gnu11 -O2 -g -mcx16 -msse2 -D_GNU_SOURCE -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-common -fwrapv -ftrivial-auto-var-init=zero -fzero-call-used-regs=used-gpr -fstack-protector-strong -Wempty-body -Wendif-labels -Wexpansion-to-defined -Wformat-overflow=2 -Wformat-security -Wformat-y2k -Wignored-qualifiers -Wimplicit-fallthrough=2 -Winit-self -Wmissing-format-attribute -Wmissing-prototypes -Wnested-externs -Wold-style-declaration -Wold-style-definition -Wredundant-decls -Wshadow=local -Wstrict-prototypes -Wtype-limits -Wundef -Wvla -Wwrite-strings -Wno-missing-include-dirs -Wno-psabi -Wno-shift-negative-value -isystem /usr/local/google/home/xuehaohu/Develop/qemu/linux-headers -isystem linux-headers -iquote . -iquote /usr/local/google/home/xuehaohu/Develop/qemu -iquote /usr/local/google/home/xuehaohu/Develop/qemu/include -iquote /usr/local/google/home/xuehaohu/Develop/qemu/host/include/x86_64 -iquote /usr/local/google/home/xuehaohu/Develop/qemu/host/include/generic -iquote /usr/local/google/home/xuehaohu/Develop/qemu/tcg/x86_64 -pthread -fPIE -D_FILE_OFFSET_BITS=64 -D__USE_FILE_OFFSET64 -D__USE_LARGEFILE64 -DUSE_POSIX_ACLS=1 -isystem /usr/include/mit-krb5 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DNCURSES_WIDECHAR=1 -D_REENTRANT -DSTRUCT_IOVEC_DEFINED -isystem../linux-headers -isystemlinux-headers -DCOMPILING_PER_TARGET '-DCONFIG_TARGET="aarch64-softmmu-config-target.h"' '-DCONFIG_DEVICES="aarch64-softmmu-config-devices.h"' -MD -MQ libqemu-aarch64-softmmu.a.p/hw_rdma_vmw_pvrdma_main.c.o -MF libqemu-aarch64-softmmu.a.p/hw_rdma_vmw_pvrdma_main.c.o.d -o libqemu-aarch64-softmmu.a.p/hw_rdma_vmw_pvrdma_main.c.o -c ../hw/rdma/vmw/pvrdma_main.c
../hw/rdma/vmw/pvrdma_main.c:23:10: fatal error: hw/qdev-properties.h: No such file or directory
   23 | #include "hw/qdev-properties.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
make: *** [Makefile:170: run-ninja] Error 1
```

Effort: pvRDMA