pvrdma: fix rdma rdma_mux channel backend ref
...char device has been renamed to CharFrontend

```
vmw_pvrdma_qp_ops.c.o -c ../hw/rdma/vmw/pvrdma_qp_ops.c
In file included from ../hw/rdma/vmw/../rdma_rm.h:20,
                 from ../hw/rdma/vmw/pvrdma_qp_ops.c:19:
../hw/rdma/vmw/../rdma_backend_defs.h:34:5: error: unknown type name ‘CharBackend’; did you mean ‘ChardevBackend’?
   34 |     CharBackend *chr_be;
      |     ^~~~~~~~~~~
      |     ChardevBackend
In file included from ../hw/rdma/vmw/pvrdma_qp_ops.c:20:
../hw/rdma/vmw/../rdma_backend.h:62:23: error: unknown type name ‘CharBackend’; did you mean ‘ChardevBackend’?
   62 |                       CharBackend *mad_chr_be);
      |                       ^~~~~~~~~~~
      |                       ChardevBackend
In file included from ../hw/rdma/vmw/pvrdma_qp_ops.c:24:
../hw/rdma/vmw/pvrdma.h:97:5: error: unknown type name ‘CharBackend’; did you mean ‘ChardevBackend’?
   97 |     CharBackend mad_chr;
      |     ^~~~~~~~~~~
      |     ChardevBackend
```

Effort: pvRDMA