pvrdma: remove hw/meson entry for pcmcia
This is causing config failure, and the folder is not
present in current qemu tree.

```
keycodemapdb| Subproject keycodemapdb finished.

../hw/meson.build:55:0: ERROR: Nonexistent build file 'hw/pcmcia/meson.build'

A full log can be found at /usr/local/google/home/xuehaohu/Develop/qemu/build/meson-logs/meson-log.txt

ERROR: meson setup failed

``

Effort: pvRDMA