pvrdma: fix gnu_source_prefix var missing issue
```
Header "asm/hwprobe.h" has symbol "RISCV_HWPROBE_EXT_ZBA" : NO

../meson.build:3136:23: ERROR: Unknown variable "gnu_source_prefix".

A full log can be found at /usr/local/google/home/xuehaohu/Develop/qemu/build/meson-logs/meson-log.txt

ERROR: meson setup failed
```

TESTED: via local config.

Effort: pvRDMA