pvrdma: s/TARGET_PAGE_SIZE/qemu_target_page_size()/g
...The global marco has been phasing out, to favor
binary specific function for page size selection
flexibility. 4Kib, 16Kib, and 64Kib are what guest
can use, the global marco no longer meets modern needs.

```
p/hw_rdma_rdma_rm.c.o -c ../hw/rdma/rdma_rm.c
../hw/rdma/rdma_rm.c: In function ‘rdma_rm_alloc_mr’:
../hw/rdma/rdma_rm.c:223:35: error: ‘TARGET_PAGE_SIZE’ undeclared (first use in this function); did you mean ‘TARGET_LONG_SIZE’?
  223 |         mr->virt += (mr->start & (TARGET_PAGE_SIZE - 1));
      |                                   ^~~~~~~~~~~~~~~~
      |                                   TARGET_LONG_SIZE
../hw/rdma/rdma_rm.c:223:35: note: each undeclared identifier is reported only once for each function it appears in
../hw/rdma/rdma_rm.c: In function ‘rdma_rm_dealloc_mr’:
../hw/rdma/rdma_rm.c:264:39: error: ‘TARGET_PAGE_SIZE’ undeclared (first use in this function); did you mean ‘TARGET_LONG_SIZE’?
  264 |             mr->virt -= (mr->start & (TARGET_PAGE_SIZE - 1));
      |                                       ^~~~~~~~~~~~~~~~
      |                                       TARGET_LONG_SIZE
[1736/3801] Compiling C object libqemu-aarch64-softmmu.a.p/hw_arm_smmuv3.c.o
```

Effort: pvRDMA