pvrdma: pvrdma_class_init: fix compiler error
```
In file included from ../hw/rdma/vmw/pvrdma_main.c:16:
../hw/rdma/vmw/pvrdma_main.c: In function ‘pvrdma_class_init’:
/usr/local/google/home/xuehaohu/Develop/qemu/include/qemu/osdep.h:279:35: error: call to ‘qemu_build_not_reached_always’ declared with attribute error: code path is reachable
  279 | #define qemu_build_not_reached()  qemu_build_not_reached_always()
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/google/home/xuehaohu/Develop/qemu/include/hw/core/qdev.h:958:13: note: in expansion of macro ‘qemu_build_not_reached’
  958 |             qemu_build_not_reached();                                   \
      |             ^~~~~~~~~~~~~~~~~~~~~~
../hw/rdma/vmw/pvrdma_main.c:712:5: note: in expansion of macro ‘device_class_set_props’
  712 |     device_class_set_props(dc, pvrdma_dev_properties);
      |     ^~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:170: run-ninja] Error 1
make[1]: Leaving directory '/usr/local/google/home/xuehaohu/Develop/qemu/build'
make: *** [GNUmakefile:6: build] Error 2
```

Frankly I don't know why my change to qdev.h worked
around the compilation error. All I intended was to
print out the actual name of last element, to debug.

Likly that print statement prevented the error from
being triggered...ouch..

This probably need a better fix.

Effort: pvRDMA